### ISSUE TITLE
rain function

### ISSUE THREAD

**Issue by RocksteadyTC** [CaptainMeatloaf/TurtleBot#1]
I'd like to rain shells on all my turtles in the chat. 

1. send TRTL to TurtleBot
2. when TRTL balance in TurtleBot surpasses 50k, bot says 
`"TUT TUT, IT LOOKS LIKE RAIN ..."`
3. timer for 60 seconds
4. after timer, bot says
`IT BEGINS TO RAIN!! YOU NOW HAVE 60 SECONDS TO INPUT YOUR TRTL WALLET ADDRESS`
5. 60 seconds elapses, TurtleBot makes a list of all unique wallet addresses
6. Bonus if the bot doesnt acknowledge anyone who hasn't spoken in the last hour.
7. Bot sends an equal share to each qualified TRTL wallet that was pasted during 60 seconds of rain.
8. 30 second timer
9. Bot announces 
`80244 TRTL WAS GIVEN TO 28 TURTLES`
`SEND TRTL TO TRTLbh897dcd2g87egf927h4f908h20808h08h08h098hj039ud2 TO MAKE IT RAIN AGAIN!`

**Comment by iwoojoo** [comment]
might be better that the bot just crawls #wallets and then compares @username+wallet to last active user of chat. if the user has a wallet posted in the #wallet and was active in the general = tip.

**Comment by MoonMoonDogo** [comment]
There is now a separate bot for making it rain: https://github.com/turtlecoin/rain-turtle
So I guess this issue can  be closed.
