### ISSUE TITLE
Welcome function

### ISSUE THREAD

**Issue by dream9x** [CaptainMeatloaf/TurtleBot#2]
the function would simply print the statement

"Welcome. Visit gettingstarted.turtlecoin.lol for wallets and mining.turtlecoin.lol for mining. Share your wallet address on #wallets for a introductory tip."

**Comment by CaptainMeatloaf** [comment]
I'd propose making this automatic when someone joins, not manually triggered

**Comment by RocksteadyTC** [comment]
I'm open to suggestions to other community resources, but I just wanted to keep it short so it actually gets read from start to finish.

>Welcome **User**! Get Started -> **GetStarted.Turtlecoin.lol** start mining -> **Mining.TurtleCoin.lol**. When your wallet has been created, post it in #wallets so people can tip you

**Comment by CaptainMeatloaf** [comment]
There is the option of making the message longer and sending it via DM too

**Comment by RocksteadyTC** [comment]
The DM, in my opinion, should be a URL list of our community resources. At the least, those URLs should contain all of our DNS forwards to the various resources.

**Comment by CaptainMeatloaf** [comment]
A list of those would be useful

**Comment by RocksteadyTC** [comment]
Working on it

**Comment by RocksteadyTC** [comment]
```

www.turtlecoin.lol        - Web Page
blog.turtlecoin.lol       - Dev Blog
chat.turtlecoin.lol       - Community Chat
meta.turtlecoin.lol       - Meta-forum (proposals, bugs, notes)
twitter.turtlecoin.lol    - Official Twitter
reddit.turtlecoin.lol     - Community Subreddit
github.turtlecoin.lol     - Source Code
download.turtlecoin.lol   - Releases
getstarted.turtlecoin.lol - Getting Started Guide
mining.turtlecoin.lol     - Mining Guide
wiki.turtlecoin.lol       - TurtleCoin Wiki
wallet.turtlecoin.lol     - TurtleCoin Paper Wallet
supply.turtlecoin.lol     - Info about TRTL Supply

```

**Comment by CaptainMeatloaf** [comment]
This has been replaced with a welcome channel instead.
