### ISSUE TITLE
!faq command

### ISSUE THREAD

**Issue by heyadjoining** [CaptainMeatloaf/TurtleBot#6]
A Frequently Asked Questions bot that would need a new role added.
I've noticed a a lot of people actually trying to help and inform people of the actual community aspect of TurtleCoin have to keep up with a lot of questions at the same time. An `@@sensei`/helper role could be added for people that really go to big extents to help everyone with their questions.
Furthermore, a !faq command that can only be used by people with said role linked to [this](https://github.com/turtlecoin/docs/blob/master/FAQ.md) list and spits out a numbered faq would be useful.

Usage example:
- New person reaches general, the most common go-to channel for discord servers. They have some questions regarding their hashrate.
- A person replies that the best channel to get help on stuff is to go to #help where most `@@sensei` live.
-Person A goes to said channel and ask the question, "Hey guys, how do I check my hashrate?"
 - `@@sensei` replies with `!faq 5`
- Bot spits out the answer from the list 
- If they were not using xmr-stak, helping goes as usual

It is not meant to alienate but to assist people into providing help and answers to concerns. 
The FAQ list file should be updated to have some numbering for this to have a more lasting benefit.
Question 5 seems like a very trivial use for it and was just intended as an example. There's some really technicall and legit concerns in there though.
The role is not needed for the bot, but I think it's a smart addition to prevent spamming.

Thank you!

**Comment by CaptainMeatloaf** [comment]
My proposal would be to allow people with the mod role to add custom 'tags' to the bot.

IE, they type "!addtag myhashrate <message here>", and then to get the bot to output that message they (or anyone else) would type "!tag myhashrate" to get the bot to output that message.

This would only work in the #help channel. Does that sound good?

**Comment by heyadjoining** [comment]
That actually works way better, more expandable and easy to remember.
Great! I really like the sound of that.

**Comment by CaptainMeatloaf** [comment]
Complete in the latest set of commits!
